package scalatex.site

import scalatags.Text.all.Frag
import ammonite.ops.FilePath
import ammonite.ops.ResourcePath

/**
 * Metadata that is code generated by scalatex-sbt-plugin.
 */
trait SiteInfo {
  /** Url of the project. */
  def url: String
  /** Working directory of the project. */
  def wd: FilePath
  /** Output path for generated site. */
  def output: FilePath
  def extraAutoResources: Seq[ResourcePath]
  def extraManualResources: Seq[ResourcePath]
  /** Root directory for all .scalatex files. */
  def scalatexFilesRoot: FilePath
  /** Listing of all .scalatex file and their corresponding frags. */
  def scalatexFiles: Map[String, Frag]
  /** The root/entrypoint/source for this site. */
  def index: Frag
}
